"""A tiny SVG "whiteboard" kit for course infographics.

Boards are drawn in the style of the session whiteboards: dashed colour-coded
groups, pastel cards with a bold title and monospace body lines, and labelled
arrows. Everything is plain SVG so the images stay sharp at any zoom, work in
an <img>, and can be regenerated by re-running the definition scripts.

Usage:
    from board import Board
    b = Board(900, 500, "Title", "optional subtitle")
    g = b.group(20, 90, 400, 300, "Ingestion", "orange")
    c = b.card(40, 130, 360, None, "loader.py", ["reads files", "retries"], "orange")
    b.arrow(c.right(), (600, 200), label="save")
    b.save("static/img/x.svg")
"""

from __future__ import annotations

import html
import math
import random
import textwrap
from dataclasses import dataclass
from pathlib import Path

MONO = "'Cascadia Code','JetBrains Mono','SF Mono',Menlo,Consolas,'Liberation Mono',monospace"
SANS = "'Inter','Segoe UI','Helvetica Neue',Arial,sans-serif"

PALETTE = {
    "blue": {"stroke": "#1c7ed6", "fill": "#e7f5ff", "text": "#1864ab"},
    "green": {"stroke": "#2f9e44", "fill": "#ebfbee", "text": "#2b8a3e"},
    "orange": {"stroke": "#e8590c", "fill": "#fff4e6", "text": "#c2410c"},
    "purple": {"stroke": "#7048e8", "fill": "#f3f0ff", "text": "#5f3dc4"},
    "red": {"stroke": "#e03131", "fill": "#fff5f5", "text": "#c92a2a"},
    "teal": {"stroke": "#0c8599", "fill": "#e3fafc", "text": "#0b7285"},
    "yellow": {"stroke": "#e8a300", "fill": "#fff9db", "text": "#b35c00"},
    "pink": {"stroke": "#d6336c", "fill": "#fff0f6", "text": "#c2255c"},
    "grey": {"stroke": "#6c757d", "fill": "#f8f9fa", "text": "#343a40"},
    "dark": {"stroke": "#1f2937", "fill": "#1f2937", "text": "#ffffff"},
}

INK = "#343a40"
FAINT = "#868e96"
CHAR_W = 0.6  # monospace advance width, in em


def esc(value: str) -> str:
    return html.escape(value, quote=True)


def wrap(line: str, max_chars: int) -> list[str]:
    if len(line) <= max_chars:
        return [line]
    return textwrap.wrap(line, max_chars, break_long_words=False, break_on_hyphens=False) or [line]


@dataclass
class Box:
    x: float
    y: float
    w: float
    h: float

    def top(self, t: float = 0.5):
        return (self.x + self.w * t, self.y)

    def bottom(self, t: float = 0.5):
        return (self.x + self.w * t, self.y + self.h)

    def left(self, t: float = 0.5):
        return (self.x, self.y + self.h * t)

    def right(self, t: float = 0.5):
        return (self.x + self.w, self.y + self.h * t)

    @property
    def cx(self):
        return self.x + self.w / 2

    @property
    def cy(self):
        return self.y + self.h / 2


class Board:
    def __init__(self, width: int, height: int, title: str = "", subtitle: str = "",
                 seed: int = 7, title_color: str = "blue"):
        self.w, self.h = width, height
        self.parts: list[str] = []
        self.overlay: list[str] = []  # labels drawn above arrows
        self.rng = random.Random(seed)
        self.markers: set[str] = set()
        self.title = title
        if title:
            color = PALETTE[title_color]["text"]
            self.parts.append(
                f'<text xml:space="preserve" x="{width / 2}" y="44" text-anchor="middle" font-family="{MONO}" '
                f'font-size="24" font-weight="700" fill="{color}">{esc(title)}</text>'
            )
        if subtitle:
            self.parts.append(
                f'<text xml:space="preserve" x="{width / 2}" y="70" text-anchor="middle" font-family="{SANS}" '
                f'font-size="14" fill="{FAINT}">{esc(subtitle)}</text>'
            )

    # ------------------------------------------------------------------ shapes

    def _jitter(self, amount: float = 1.2) -> float:
        return self.rng.uniform(-amount, amount)

    def _sketch_rect(self, x, y, w, h, stroke, width=1.1, opacity=0.45):
        """A second, slightly offset rounded outline: gives the hand-drawn feel."""
        j = self._jitter
        self.parts.append(
            f'<rect x="{x + j(1.5):.1f}" y="{y + j(1.5):.1f}" width="{w + j(1.5):.1f}" '
            f'height="{h + j(1.5):.1f}" rx="10" fill="none" stroke="{stroke}" '
            f'stroke-width="{width}" stroke-opacity="{opacity}"/>'
        )

    def group(self, x, y, w, h, label: str = "", color: str = "grey", label_pos: str = "top") -> Box:
        c = PALETTE[color]
        self.parts.append(
            f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="14" fill="{c["fill"]}" '
            f'fill-opacity="0.35" stroke="{c["stroke"]}" stroke-width="2" stroke-dasharray="9 6"/>'
        )
        if label:
            ty = y + 26 if label_pos == "top" else y + h - 12
            self.parts.append(
                f'<text xml:space="preserve" x="{x + w / 2}" y="{ty}" text-anchor="middle" font-family="{MONO}" '
                f'font-size="16" font-weight="700" fill="{c["text"]}">{esc(label)}</text>'
            )
        return Box(x, y, w, h)

    def card(self, x, y, w, h, title: str = "", lines: list[str] | None = None, color: str = "blue",
             size: int = 12, align: str = "center", title_size: int | None = None,
             bullets: bool = False, dashed: bool = False) -> Box:
        c = PALETTE[color]
        lines = lines or []
        title_size = title_size or size + 2
        pad = 12
        max_chars = max(8, int((w - 2 * pad) / (size * CHAR_W)))
        title_chars = max(8, int((w - 2 * pad) / (title_size * CHAR_W)))
        title_lines = wrap(title, title_chars) if title else []
        body: list[str] = []
        for line in lines:
            prefix = "• " if bullets and line else ""
            wrapped = wrap(prefix + line, max_chars)
            body.extend([wrapped[0]] + ["  " + t if bullets else t for t in wrapped[1:]])
        line_h = size * 1.45
        title_h = title_size * 1.35
        content_h = len(title_lines) * title_h + (6 if title_lines and body else 0) + len(body) * line_h
        if h is None:
            h = content_h + 2 * pad
        fill = c["fill"]
        stroke = c["stroke"]
        dash = ' stroke-dasharray="6 5"' if dashed else ""
        self.parts.append(
            f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="9" fill="{fill}" '
            f'stroke="{stroke}" stroke-width="1.6"{dash}/>'
        )
        if not dashed:
            self._sketch_rect(x, y, w, h, stroke)
        ty = y + (h - content_h) / 2 + title_size
        anchor = "middle" if align == "center" else "start"
        tx = x + w / 2 if align == "center" else x + pad
        text_color = c["text"] if color != "dark" else "#ffffff"
        for t in title_lines:
            self.parts.append(
                f'<text xml:space="preserve" x="{tx}" y="{ty:.1f}" text-anchor="{anchor}" font-family="{MONO}" '
                f'font-size="{title_size}" font-weight="700" fill="{text_color}">{esc(t)}</text>'
            )
            ty += title_h
        if title_lines and body:
            ty += 6 - title_h + line_h
        elif body:
            ty = y + (h - content_h) / 2 + size
        body_color = INK if color != "dark" else "#e9ecef"
        for t in body:
            self.parts.append(
                f'<text xml:space="preserve" x="{tx}" y="{ty:.1f}" text-anchor="{anchor}" font-family="{MONO}" '
                f'font-size="{size}" fill="{body_color}">{esc(t)}</text>'
            )
            ty += line_h
        return Box(x, y, w, h)

    def cylinder(self, x, y, w, h, title: str, lines: list[str] | None = None, color: str = "purple",
                 size: int = 12) -> Box:
        c = PALETTE[color]
        ry = min(12, h * 0.12)
        self.parts.append(
            f'<path d="M{x},{y + ry} a{w / 2},{ry} 0 0 0 {w},0 v{h - 2 * ry} a{w / 2},{ry} 0 0 1 {-w},0 z" '
            f'fill="{c["fill"]}" stroke="{c["stroke"]}" stroke-width="1.6"/>'
        )
        self.parts.append(
            f'<ellipse cx="{x + w / 2}" cy="{y + ry}" rx="{w / 2}" ry="{ry}" fill="{c["fill"]}" '
            f'stroke="{c["stroke"]}" stroke-width="1.6"/>'
        )
        body = lines or []
        total = 1 + len(body)
        ty = y + ry + (h - ry) / 2 - (total - 1) * size * 0.72 + size * 0.35
        self.parts.append(
            f'<text xml:space="preserve" x="{x + w / 2}" y="{ty:.1f}" text-anchor="middle" font-family="{MONO}" '
            f'font-size="{size + 1}" font-weight="700" fill="{c["text"]}">{esc(title)}</text>'
        )
        for t in body:
            ty += size * 1.45
            self.parts.append(
                f'<text xml:space="preserve" x="{x + w / 2}" y="{ty:.1f}" text-anchor="middle" font-family="{MONO}" '
                f'font-size="{size}" fill="{INK}">{esc(t)}</text>'
            )
        return Box(x, y, w, h)

    def diamond(self, cx, cy, w, h, label: str, color: str = "yellow", size: int = 12) -> Box:
        c = PALETTE[color]
        pts = f"{cx},{cy - h / 2} {cx + w / 2},{cy} {cx},{cy + h / 2} {cx - w / 2},{cy}"
        self.parts.append(
            f'<polygon points="{pts}" fill="{c["fill"]}" stroke="{c["stroke"]}" stroke-width="1.8"/>'
        )
        lines = label.split("\n")
        ty = cy - (len(lines) - 1) * size * 0.7 + size * 0.35
        for t in lines:
            self.parts.append(
                f'<text xml:space="preserve" x="{cx}" y="{ty:.1f}" text-anchor="middle" font-family="{MONO}" '
                f'font-size="{size}" font-weight="700" fill="{c["text"]}">{esc(t)}</text>'
            )
            ty += size * 1.4
        return Box(cx - w / 2, cy - h / 2, w, h)

    def pill(self, x, y, text: str, color: str = "grey", size: int = 11, solid: bool = False,
             anchor: str = "start") -> Box:
        c = PALETTE[color]
        w = len(text) * size * CHAR_W + 18
        h = size + 10
        if anchor == "middle":
            x -= w / 2
        fill = c["stroke"] if solid else c["fill"]
        fg = "#ffffff" if solid else c["text"]
        self.parts.append(
            f'<rect x="{x:.1f}" y="{y}" width="{w:.1f}" height="{h}" rx="{h / 2}" fill="{fill}" '
            f'stroke="{c["stroke"]}" stroke-width="1.2"/>'
        )
        self.parts.append(
            f'<text xml:space="preserve" x="{x + w / 2:.1f}" y="{y + h / 2 + size * 0.36:.1f}" text-anchor="middle" '
            f'font-family="{MONO}" font-size="{size}" font-weight="700" fill="{fg}">{esc(text)}</text>'
        )
        return Box(x, y, w, h)

    def text(self, x, y, text: str, size: int = 13, color: str | None = None, weight: str = "400",
             anchor: str = "middle", family: str = MONO, italic: bool = False, line_gap: float = 1.4):
        fill = PALETTE[color]["text"] if color in PALETTE else (color or INK)
        style = ' font-style="italic"' if italic else ""
        for i, t in enumerate(text.split("\n")):
            self.parts.append(
                f'<text xml:space="preserve" x="{x}" y="{y + i * size * line_gap:.1f}" text-anchor="{anchor}" '
                f'font-family="{family}" font-size="{size}" font-weight="{weight}" fill="{fill}"{style}>'
                f'{esc(t)}</text>'
            )

    def person(self, cx, top, color: str = "grey", scale: float = 1.0, label: str = ""):
        c = PALETTE[color]["stroke"]
        r = 11 * scale
        body = top + 2 * r
        self.parts.append(
            f'<g stroke="{c}" stroke-width="{2.4 * scale}" fill="none" stroke-linecap="round">'
            f'<circle cx="{cx}" cy="{top + r}" r="{r}" fill="{PALETTE[color]["fill"]}"/>'
            f'<path d="M{cx},{body} v{24 * scale} M{cx - 16 * scale},{body + 10 * scale} h{32 * scale} '
            f'M{cx},{body + 24 * scale} l{-12 * scale},{18 * scale} M{cx},{body + 24 * scale} '
            f'l{12 * scale},{18 * scale}"/></g>'
        )
        if label:
            self.text(cx, body + 62 * scale, label, 13, color, "700")
        return Box(cx - 18 * scale, top, 36 * scale, 2 * r + 42 * scale)

    def bar(self, x, y, w, value: float, threshold: float | None = None, color: str = "green",
            h: int = 16, label: str = ""):
        c = PALETTE[color]
        self.parts.append(
            f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{h / 2}" fill="#e9ecef" stroke="#ced4da"/>'
        )
        self.parts.append(
            f'<rect x="{x}" y="{y}" width="{w * max(0.0, min(1.0, value)):.1f}" height="{h}" rx="{h / 2}" '
            f'fill="{c["stroke"]}"/>'
        )
        if threshold is not None:
            tx = x + w * threshold
            self.parts.append(
                f'<line x1="{tx}" y1="{y - 6}" x2="{tx}" y2="{y + h + 6}" stroke="{INK}" '
                f'stroke-width="2" stroke-dasharray="3 3"/>'
            )
            self.text(tx, y + h + 20, f"threshold {threshold:g}", 11, FAINT)
        if label:
            self.text(x + w + 10, y + h - 3, label, 14, color, "700", anchor="start")

    def table(self, x, y, col_widths: list[float], rows: list[list[str]], header_color: str = "blue",
              size: int = 12, row_h: float | None = None, zebra: bool = True):
        c = PALETTE[header_color]
        total_w = sum(col_widths)
        cy = y
        for r, row in enumerate(rows):
            wrapped = []
            for cell, cw in zip(row, col_widths):
                chars = max(6, int((cw - 16) / (size * CHAR_W)))
                wrapped.append([ln for part in cell.split("\n") for ln in wrap(part, chars)])
            lines = max(len(wc) for wc in wrapped)
            rh = row_h or (lines * size * 1.4 + 14)
            if r == 0:
                self.parts.append(
                    f'<rect x="{x}" y="{cy}" width="{total_w}" height="{rh}" rx="6" fill="{c["stroke"]}"/>'
                )
            elif zebra and r % 2 == 0:
                self.parts.append(
                    f'<rect x="{x}" y="{cy}" width="{total_w}" height="{rh}" fill="{c["fill"]}"/>'
                )
            cx = x
            for cell_lines, cw in zip(wrapped, col_widths):
                ty = cy + 7 + size
                for ln in cell_lines:
                    self.parts.append(
                        f'<text xml:space="preserve" x="{cx + 8}" y="{ty:.1f}" font-family="{MONO}" font-size="{size}" '
                        f'font-weight="{"700" if r == 0 else "400"}" '
                        f'fill="{"#ffffff" if r == 0 else INK}">{esc(ln)}</text>'
                    )
                    ty += size * 1.4
                cx += cw
            cy += rh
            self.parts.append(
                f'<line x1="{x}" y1="{cy}" x2="{x + total_w}" y2="{cy}" stroke="#dee2e6"/>'
            )
        return Box(x, y, total_w, cy - y)

    # ------------------------------------------------------------------ arrows

    def _marker(self, color: str) -> str:
        mid = f"ah{color.strip('#')}"
        self.markers.add(color)
        return mid

    def arrow(self, p1, p2, via: list | None = None, label: str = "", color: str = INK,
              dashed: bool = False, width: float = 1.8, curve: bool = False, label_at: float = 0.5,
              label_color: str | None = None, both: bool = False, label_dx: float = 0,
              label_dy: float = 0):
        col = PALETTE[color]["stroke"] if color in PALETTE else color
        pts = [p1] + (via or []) + [p2]
        if curve and len(pts) == 2:
            (x1, y1), (x2, y2) = pts
            mx, my = (x1 + x2) / 2, (y1 + y2) / 2
            nx, ny = -(y2 - y1), x2 - x1
            norm = math.hypot(nx, ny) or 1
            k = 0.18 * math.hypot(x2 - x1, y2 - y1)
            qx, qy = mx + nx / norm * k, my + ny / norm * k
            d = f"M{x1:.1f},{y1:.1f} Q{qx:.1f},{qy:.1f} {x2:.1f},{y2:.1f}"
            lx, ly = (mx + qx) / 2, (my + qy) / 2
        else:
            d = "M" + " L".join(f"{px:.1f},{py:.1f}" for px, py in pts)
            # label on the longest segment by default
            segs = list(zip(pts, pts[1:]))
            a, b = max(segs, key=lambda s: math.hypot(s[1][0] - s[0][0], s[1][1] - s[0][1]))
            lx, ly = a[0] + (b[0] - a[0]) * label_at, a[1] + (b[1] - a[1]) * label_at
        dash = ' stroke-dasharray="7 5"' if dashed else ""
        mid = self._marker(col)
        start = f' marker-start="url(#{mid}s)"' if both else ""
        self.parts.append(
            f'<path d="{d}" fill="none" stroke="{col}" stroke-width="{width}"{dash} '
            f'stroke-linejoin="round" marker-end="url(#{mid})"{start}/>'
        )
        if label:
            lc = PALETTE[label_color]["text"] if label_color in PALETTE else (label_color or col)
            lines = label.split("\n")
            lw = max(len(t) for t in lines) * 11 * CHAR_W + 10
            lh = len(lines) * 14 + 4
            lx += label_dx
            ly += label_dy
            self.overlay.append(
                f'<rect x="{lx - lw / 2:.1f}" y="{ly - lh / 2:.1f}" width="{lw:.1f}" height="{lh}" rx="4" '
                f'fill="#fffdf7" fill-opacity="0.95"/>'
            )
            for i, t in enumerate(lines):
                self.overlay.append(
                    f'<text xml:space="preserve" x="{lx:.1f}" y="{ly - lh / 2 + 13 + i * 14:.1f}" text-anchor="middle" '
                    f'font-family="{MONO}" font-size="11" font-weight="700" fill="{lc}">{esc(t)}</text>'
                )

    # ------------------------------------------------------------------ output

    def svg(self) -> str:
        defs = []
        for col in sorted(self.markers):
            mid = f"ah{col.strip('#')}"
            defs.append(
                f'<marker id="{mid}" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" '
                f'markerHeight="7" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="{col}"/></marker>'
            )
            defs.append(
                f'<marker id="{mid}s" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" '
                f'markerHeight="7" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="{col}"/></marker>'
            )
        head = (
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {self.w} {self.h}" '
            f'width="{self.w}" height="{self.h}" role="img" aria-label="{esc(self.title)}">'
            f'<defs>{"".join(defs)}</defs>'
            f'<rect x="0" y="0" width="{self.w}" height="{self.h}" rx="18" fill="#fffdf7"/>'
        )
        return head + "".join(self.parts) + "".join(self.overlay) + "</svg>\n"

    def save(self, path: str | Path) -> Path:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self.svg(), encoding="utf-8")
        return path
